type: "localnet"
config:
  consensus:
    timeout_commit: 5000000000
    create_empty_blocks: true
    create_empty_blocks_interval: 0
  tx_index:
    index_tags: ""
    index_all_tags: true
accounts:
  - address: darc10v74707r0n7khgn5sftmdd3lfwcgjl9kpfxtxw
    coins: [ "300000000000000udarc" ]
  - address: darc1tal4c2mgpw3zv5lpyskv86v8y3hrxa3wp2frft
    coins: [ "200000000000000udarc" ]
  - address: darc1nq2neh6pp0t35w7sd8lyrnu59mywhf25fzue3n
    coins: [ "200000000000000udarc" ]
validators:
  - name: "testnode-1"
    ip: "172.16.1.2"
    index: 1
    description:
      moniker: "testnode-1"
      identity: ""
      website: "http://172.16.1.2:26657"
      details: "testnode-1"
    key:
      address: darc10v74707r0n7khgn5sftmdd3lfwcgjl9kpfxtxw
      coin_delegate: 100000000
    config:
      rpc:
        cors_allowed_origins:
          - "*"
        laddr: "tcp://0.0.0.0:26657"
      faucet: true
  - name: "testnode-2"
    ip: "172.16.1.3"
    index: 2
    description:
      moniker: "testnode-2"
      identity: ""
      website: "http://172.16.1.3:26657"
      details: "testnode-2"
    key:
      address: darc1tal4c2mgpw3zv5lpyskv86v8y3hrxa3wp2frft
      coin_delegate: 100000000
    config:
      rpc:
        cors_allowed_origins:
          - "*"
        laddr: "tcp://0.0.0.0:26657"
  - name: "testnode-3"
    ip: "172.16.1.4"
    index: 3
    description:
      moniker: "testnode-3"
      identity: ""
      website: "http://172.16.1.4:26657"
      details: "testnode-3"
    key:
      address: darc1nq2neh6pp0t35w7sd8lyrnu59mywhf25fzue3n
      coin_delegate: 100000000
    config:
      rpc:
        cors_allowed_origins:
          - "*"
        laddr: "tcp://0.0.0.0:26657"
genesis:
  chain_id: "darchub"
  app_state:
    staking:
      params:
        bond_denom: "udarc"
    mint:
      params:
        mint_denom: "udarc"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000000"
            denom: "udarc"
        max_deposit_period: "172800s"
    crisis:
      constant_fee:
        amount: "100000000000"
        denom: "udarc"
    oracle:
      allowed_addresses:
        - address: "darc1hm0ahdz4p3aqugxucgcklsj9lzr437qdgw7wef"
#    issue:
#      tokens:
#        - owner: "darc1n8lpdv72n4vr90e8drj8903vmrafafmgcelfpx"
#          issuer: "darc1n8lpdv72n4vr90e8drj8903vmrafafmgcelfpx"
#          denom: "udarc"
#          symbol: "UDARC"
#          total_supply: 0
#          decimals: 6
#          freeze_disabled: true