type: "mainnet"
config:
  consensus:
    timeout_commit: 5000000000
    create_empty_blocks: true
    create_empty_blocks_interval: 0
  tx_index:
    index_tags: ""
    index_all_tags: true
accounts:
  - address: darc16n226c7p4fkmrgxjsclln38qthulggmr5xkkug
    coins: [ "3000001000000udarc" ]
  - address: darc1sehh6z74x04y0rzmfhn0gw7z9jl7c3a99ns0p0
    coins: [ "3000001000000udarc" ]
  - address: darc16cmu7rvtzrxqxtv84z6u9qgl2272fak8xxaexr
    coins: [ "3000001000000udarc" ]
  - address: darc1zhdr6rulr45vmve6k4nq400yzwca549c4cvmpk
    coins: [ "3000001000000udarc" ]
validators:
  - name: "testnode-1"
    ip: "node6.konstellation.tech"
    index: 1
    description:
      moniker: "node1"
      identity: ""
      website: "https://node6.konstellation.tech:26657"
      details: "mainnode-1"
    key:
      address: darc16n226c7p4fkmrgxjsclln38qthulggmr5xkkug
      coin_delegate: 1000000
    config:
      rpc:
        cors_allowed_origins:
          - "*"
        laddr: "tcp://0.0.0.0:26657"
      faucet: true
  - name: "testnode-2"
    ip: "node7.konstellation.tech"
    index: 2
    description:
      moniker: "node2"
      identity: ""
      website: "https://node7.konstellation.tech:26657"
      details: "mainnode-2"
    key:
      address: darc1sehh6z74x04y0rzmfhn0gw7z9jl7c3a99ns0p0
      coin_delegate: 1000000
    config:
      rpc:
        cors_allowed_origins:
          - "*"
        laddr: "tcp://0.0.0.0:26657"
  - name: "testnode-3"
    ip: "node8.konstellation.tech"
    index: 3
    description:
      moniker: "node3"
      identity: ""
      website: "https://node8.konstellation.tech:26657"
      details: "mainnode-3"
    key:
      address: darc16cmu7rvtzrxqxtv84z6u9qgl2272fak8xxaexr
      coin_delegate: 1000000
    config:
      rpc:
        cors_allowed_origins:
          - "*"
        laddr: "tcp://0.0.0.0:26657"
  - name: "testnode-4"
    ip: "206.81.29.202"
    index: 4
    description:
      moniker: "node4"
      identity: ""
      website: "https://206.81.29.202:26657"
      details: "mainnode-4"
    key:
      address: darc1zhdr6rulr45vmve6k4nq400yzwca549c4cvmpk
      coin_delegate: 1000000
    config:
      rpc:
        cors_allowed_origins:
          - "*"
        laddr: "tcp://0.0.0.0:26657"
genesis:
  chain_id: "darchub"
  app_state:
    staking:
      params:
        bond_denom: "udarc"
    mint:
      params:
        mint_denom: "udarc"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000000"
            denom: "udarc"
        max_deposit_period: "172800s"
    crisis:
      constant_fee:
        amount: "100000000000"
        denom: "udarc"
    oracle:
      allowed_addresses:
        - address: "darc1zar995wlx4x5dlevp6rkk26s9r2n2uswwdchft"
#    issue:
#      tokens:
#        - owner: "darc1n8lpdv72n4vr90e8drj8903vmrafafmgcelfpx"
#          issuer: "darc1n8lpdv72n4vr90e8drj8903vmrafafmgcelfpx"
#          denom: "udarc"
#          symbol: "UDARC"
#          total_supply: 0
#          decimals: 6
#          freeze_disabled: true